### ISSUE TITLE
ADNI data processing

### ISSUE THREAD

**Issue by naji-s** [TAMU-VITA/Self-PU#28]
Hi,

Thanks so much for having your code and data processing code on github!

I am trying to process the ADNI dataset and follow your processing scheme. I noticed that on page 6 of your work [here](https://arxiv.org/pdf/2006.11280.pdf), you mention SUVR being no smaller than 1.08 is used to label a data point as positive (beside it being clinically positive). But below I see you also incorporate SUVR==1.18, and I am not sure where this value comes from, and why T (which I am assuming is the true label of the data) is set to 1 when SUVR>=1.18 but not when SUVR>=1.08?

https://github.com/VITA-Group/Self-PU/blob/a0e332ae4f8110e2490d597876e36bf837e1060f/adni_dataset.py#L189-L194

Thank you!

**Comment by xxchenxx** [comment]
Hello,

Thank you for your interest in our project! I must admit it has been quite a while since we worked on this project, and some details escape me at the moment. I'll try to consult with my collaborators and follow up with you promptly.

Best regards,

**Comment by naji-s** [comment]
Thank you! Looking forward to hearing back from you on this!
